### ISSUE TITLE
Навык не работает на Станции

### ISSUE THREAD

**Issue by ASMfreaK** [popstas/yandex-dialogs-whatis#2]
Вторая память не нуждается в графике, насколько я понимаю, а значит её можно довольно легко адаптировать для Станции. Обладаю Станцией и готов помогать тестировать.

**Comment by popstas** [comment]
Пропустил ваше предложение, я включил навык для станции примерно месяц назад.
Думаю в праздники улучшить навык, если у вас получалось пользоваться навыком для решения каких-то задач, интересно было бы услышать критику )
Я сам неделю назад купил Irbis колонку, у меня интерес к тому, чтобы сделать навык лучше, резко повысился, на телефоне и десктопе пользоваться было неудобно, а с появлением колонки я начинаю видеть в этом смысл.
